# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=datetime.datetime(2017, 3, 15, 22, 7, 41, 783437, tzinfo=utc), editable=False)),
                ('condition', models.IntegerField(choices=[(0, 'alcohol'), (10, 'Food'), (20, 'Tobacco'), (30, 'Drugs'), (40, 'Cannabis'), (50, 'Cocaine'), (60, 'Heroin'), (70, 'ATS'), (80, 'Gambling'), (90, 'Video Games'), (100, 'Internet'), (110, 'Sex'), (120, 'Shopping'), (130, 'Work'), (140, 'Masturbation'), (150, 'Illegal Drugs'), (160, 'Legal Drugs'), (170, 'Caffeine'), (180, 'Being Bitchy'), (190, 'masturbation'), (200, 'Marijuana'), (210, 'Nicotine')])),
                ('notes', models.TextField(blank=True, default='')),
                ('money', models.IntegerField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addictions',
                'verbose_name': 'Addiction',
            },
        ),
    ]
