# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addiction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addictions',
            name='money',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='addictions',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='addictions',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 22, 9, 40, 46004, tzinfo=utc), editable=False),
        ),
    ]
